# Generated by Django 4.1.7 on 2023-05-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='id',
        ),
        migrations.AlterField(
            model_name='child',
            name='child_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
