# Generated by Django 4.1.7 on 2023-05-20 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_child_child_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
