# Generated by Django 4.1.7 on 2023-05-20 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_child_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
