# Generated by Django 4.1.7 on 2023-05-20 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_child_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
