# Generated by Django 4.1.7 on 2023-05-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_child_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
