# Generated by Django 4.1.7 on 2023-05-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_child_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='medical_condition',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
