# Generated by Django 4.1.7 on 2023-05-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_child_medical_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='child_id',
            new_name='id',
        ),
    ]
